### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithDexForDebug'

### ISSUE THREAD

**Issue by matskr90dev** [PayU/paytouch-android#3]
I use your library in my application and with paytouch-android 1.3.3 everything works fine. But after upgrade to 1.3.4 I get the following errors:

	Error:com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

	Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
	> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_79\bin\java.exe'' finished with non-zero exit value 1

Firstly I thought that I exceeded 65k methods limit in my app. But after create empty project in Android Studio the problem occurs also.

How reproduce this issue?
1. Create new empty project in Android Studio 1.5
2. Add dependencies to paytouch-android and run app

**Comment by krokers** [comment]
Thank you for reporting the issue. We are investigating the problem.

**Comment by krokers** [comment]
It was a problem with dependency library used by paytouch SDK. Bugfix has been already pushed to master.
